# Generated by Django 2.1 on 2020-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgregateData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, db_column='year', max_length=4, null=True)),
                ('month', models.CharField(blank=True, db_column='month', max_length=4, null=True)),
                ('random_id_code', models.CharField(blank=True, db_column='random_id_code', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=4, null=True)),
                ('random_name', models.CharField(blank=True, db_column='random_name', max_length=100, null=True)),
                ('random_amount', models.DecimalField(blank=True, db_column='random_amount', decimal_places=2, max_digits=18, null=True)),
                ('random_count', models.DecimalField(blank=True, db_column='random_count', decimal_places=2, max_digits=18, null=True)),
                ('random_percent', models.DecimalField(blank=True, db_column='random_percent', decimal_places=2, max_digits=2, null=True)),
                ('rule_1', models.DecimalField(blank=True, db_column='rule_1', decimal_places=2, max_digits=18, null=True)),
                ('rule_2', models.DecimalField(blank=True, db_column='rule_2', decimal_places=2, max_digits=18, null=True)),
                ('rule_3', models.DecimalField(blank=True, db_column='rule_3', decimal_places=2, max_digits=18, null=True)),
                ('rule_4', models.DecimalField(blank=True, db_column='rule_4', decimal_places=2, max_digits=18, null=True)),
                ('created_dtime', models.DateTimeField(blank=True, db_column='created_dtime', null=True)),
            ],
            options={
                'db_table': 'Agregate_Data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetailData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('random_name', models.CharField(blank=True, db_column='random_name', max_length=25, null=True)),
                ('random_amount', models.DecimalField(blank=True, db_column='random_amount', decimal_places=2, max_digits=18, null=True)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('type', models.CharField(blank=True, db_column='type', max_length=10, null=True)),
                ('random_id_code', models.CharField(blank=True, db_column='random_id_code', max_length=50, null=True)),
                ('created_dtime', models.DateTimeField(blank=True, db_column='created_dtime', null=True)),
            ],
            options={
                'db_table': 'Detail_Data',
                'managed': True,
            },
        ),
    ]
